# Generated by Django 2.1 on 2019-12-07 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Addresses',
            new_name='Hangouts_Model',
        ),
    ]
