# Generated by Django 3.0 on 2019-12-13 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps_app', '0003_auto_20191207_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='hangouts_model',
            name='add_10',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='hangouts_model',
            name='add_4',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='hangouts_model',
            name='add_5',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='hangouts_model',
            name='add_6',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='hangouts_model',
            name='add_7',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='hangouts_model',
            name='add_8',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='hangouts_model',
            name='add_9',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='hangouts_model',
            name='add_3',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
