# Generated by Django 3.0 on 2019-12-14 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps_app', '0004_auto_20191213_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='hangouts_model',
            name='cntpnt_rad',
            field=models.IntegerField(default=400),
        ),
        migrations.AlterField(
            model_name='hangouts_model',
            name='category',
            field=models.CharField(choices=[('cafe', 'Cafes'), ('bar', 'Bars'), ('gym', 'Gyms'), ('restaurant', 'Restaurants'), ('shopping_mall', 'Shopping Malls'), ('subway_station', 'Subway Stations')], max_length=50),
        ),
    ]
