# Generated by Django 3.0 on 2019-12-14 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps_app', '0005_auto_20191214_0332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hangouts_model',
            old_name='cntpnt_rad',
            new_name='centerpoint_radius',
        ),
    ]
